spring:
  application:
    name: discovery-service
# Configure this Discovery Server
#TODO here you add configurations for server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 3000
  waitTimeInMsWhenSyncEmpty: 0
  address: 0.0.0.0


logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    com.apress.cems: DEBUG
